<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../DesktopShrine.Abstractions/DesktopShrine.Abstractions.csproj"/><ProjectReference Include="../DesktopShrine.Storage/DesktopShrine.Storage.csproj"/><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
